[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-cctv"
version = "0.1.0"
description = "AI CCTV edge node and AI server package"
requires-python = ">=3.11"
dependencies = [
]

[project.optional-dependencies]
edge-node = [
    "fastapi",
    "uvicorn",
    "paho-mqtt",
    "psutil",
    "smbus2",
]
ai-server = [
    "torch",
    "transformers>=4.51.0",
    "accelerate",
    "huggingface-hub",
    "pillow",
    "qwen-vl-utils",
    "bitsandbytes",
    "opencv-python",
    "ultralytics",
    "numpy",
    "matplotlib",
    "scipy",
    "pyyaml",
    "requests",
    "paho-mqtt",
    "psutil",
    "insightface",
    "onnxruntime",
    "discord.py>=2.0.0",
    "PyQt5",
]
vision-demo = [
    "mediapipe",
    "torch",
]

[project.scripts]
ai-cctv = "ai_cctv.ai_server.server_run:main"
ai-cctv-edge = "ai_cctv.edge_node.main:main"
ai-cctv-edge-mqtt-broker = "ai_cctv.edge_node.monitoring.mqtt_broker:main"
ai-cctv-edge-monitor = "ai_cctv.edge_node.monitoring.resource_monitor_publisher:main"
ai-cctv-edge-backup-recovery = "ai_cctv.edge_node.backup_recovery_server:main"
ai-cctv-ai-server = "ai_cctv.ai_server.server_run:main"

[tool.setuptools.packages.find]
where = ["src"]
